name: Deploy to QA

on: 
  pull_request:
    types: 
      -closed
    
jobs:
  pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
